---
title: "Explore data"
author: "Puck Quarles van Ufford"
date: today
format: html
---

# Set up

```{r}
#| label: packages
#| message: false
#| echo: true

library("tidyverse")
library("survival")
library("survminer")
```

# Load data

```{r}
#| label: load_data
#| message: false
#| echo: true

data_train_os <- read_tsv(file = "../data/03_data_train_os.tsv")
data_train_dfs <- read_tsv(file = "../data/03_data_train_dfs.tsv")
data_test <- read_tsv(file = "../data/02_data_test.tsv")
```

# Kaplan-Meier curves

```{r}
#| label: km_os
#| message: false
#| echo: true

data_os <- data_train_os |> 
  select(patient_id,
         os_status,
         years_to_os_event) |> 
  mutate(data = "train")

data_os <- data_test |> 
  select(patient_id = PATIENT_ID,
         os_status = OS_STATUS,
         years_to_os_event = YEARS_TO_OS_EVENT) |> 
  mutate(data = "test") |> 
  bind_rows(data_os) |> 
  mutate(data = factor(data,
                        levels = c("train",
                                   "test")))

data_os |> 
  summarise(median(years_to_os_event))

data_os |> 
  group_by(data,
           os_status) |> 
  summarise(n())

fit_os <- survfit(Surv(years_to_os_event, 
                       os_status) ~ data, 
                  data = data_os)

ggsurvplot(
  fit = fit_os,
  data = data_os,
  title = "Kaplan-Meier plot for OS",
  xlab = "Time (years after surgery)",
  ylab = "OS probability",
  ylim = c(0, 1),
  legend = "bottom",
  risk.table = F,
  pval = TRUE,
  pval.method = TRUE,
  palette = c("#648FFF",
              "#FE6100"),
  ggtheme = theme_bw()
) 

ggsave("../results/04_KM_OS.png",
       width = 8,
       height = 4.5)
```

```{r}
#| label: km_dfs
#| message: false
#| echo: true

data_dfs <- data_train_dfs |> 
  select(patient_id,
         dfs_status,
         years_to_dfs_event) |> 
  mutate(data = "train")

data_dfs <- data_test |> 
  select(patient_id = PATIENT_ID,
         dfs_status = DFS_STATUS,
         years_to_dfs_event = YEARS_TO_DFS_EVENT) |> 
  mutate(data = "test") |> 
  bind_rows(data_dfs) |> 
  mutate(data = factor(data,
                        levels = c("train",
                                   "test")))

data_dfs |> 
  summarise(median(years_to_dfs_event))

data_dfs |> 
  group_by(data,
           dfs_status) |> 
  summarise(n())

fit_dfs <- survfit(Surv(years_to_dfs_event, 
                        dfs_status) ~ data, 
                  data = data_dfs)

ggsurvplot(
  fit = fit_dfs,
  data = data_dfs,
  title = "Kaplan-Meier plot for DFS",
  xlab = "Time (years after surgery)",
  ylab = "DFS probability",
  ylim = c(0, 1),
  legend = "bottom",
  risk.table = F,
  pval = TRUE,
  pval.method = TRUE,
  palette = c("#648FFF",
              "#FE6100"),
  ggtheme = theme_bw()
) 

ggsave("../results/04_KM_DFS.png",
       width = 8,
       height = 4.5)
```
