---
title: "Cox models"
author: "Puck Quarles van Ufford"
date: today
format: html
---

# Set up

```{r}
#| label: packages
#| message: false
#| echo: true

library("tidyverse")
library("glmnet")
library("survival")
library("caret")
library("pROC")
```

```{r}
#| label: seed
#| echo: true

set.seed(8)
```

# Load data

```{r}
#| label: load_data
#| message: false
#| echo: true

data_os <- read_tsv(file = "../data/03_data_train_os.tsv")
data_os_noNLP <- read_tsv(file = "../data/03_data_train_os_noNLP.tsv")
data_os_nogenomic <- read_tsv(file = "../data/03_data_train_os_nogenomic.tsv")
data_os_noNLPgenomic <- read_tsv(file = "../data/03_data_train_os_noNLPgenomic.tsv")

data_dfs <- read_tsv(file = "../data/03_data_train_dfs.tsv")
data_dfs_noNLP <- read_tsv(file = "../data/03_data_train_dfs_noNLP.tsv")
data_dfs_nogenomic <- read_tsv(file = "../data/03_data_train_dfs_nogenomic.tsv")
data_dfs_noNLPgenomic <- read_tsv(file = "../data/03_data_train_dfs_noNLPgenomic.tsv")
```

# Settings

```{r}
#| label: settings
#| echo: true

regularization <- FALSE
alpha <- 1 # 0.5 for elastic-net, 1 for lasso, 0 for ridge

p_value_threshold <- 0.05

setting <- ifelse(regularization,
                  case_when(alpha == 1 ~ "lasso",
                            alpha == 0.5 ~ "elastic-net",
                            TRUE ~ "ERROR"),
                  "classic")

setting
```

# Set up cross-validation

```{r}
#| label: 5_fold_CV
#| echo: true

folds_os <- createFolds(data_os$os_status,
                        k = 5,
                        list = TRUE,
                        returnTrain = FALSE)
folds_os_noNLP <- createFolds(data_os_noNLP$os_status,
                              k = 5,
                              list = TRUE,
                              returnTrain = FALSE)
folds_os_nogenomic <- createFolds(data_os_nogenomic$os_status,
                                  k = 5,
                                  list = TRUE,
                                  returnTrain = FALSE)
folds_os_noNLPgenomic <- createFolds(data_os_noNLPgenomic$os_status,
                                     k = 5,
                                     list = TRUE,
                                     returnTrain = FALSE)

folds_dfs <- createFolds(data_dfs$dfs_status,
                         k = 5,
                         list = TRUE,
                         returnTrain = FALSE)
folds_dfs_noNLP <- createFolds(data_dfs_noNLP$dfs_status,
                               k = 5,
                               list = TRUE,
                               returnTrain = FALSE)
folds_dfs_nogenomic <- createFolds(data_dfs_nogenomic$dfs_status,
                                   k = 5,
                                   list = TRUE,
                                   returnTrain = FALSE)
folds_dfs_noNLPgenomic <- createFolds(data_dfs_noNLPgenomic$dfs_status,
                                      k = 5,
                                      list = TRUE,
                                      returnTrain = FALSE)
```

# Cox model workflow

```{r}
#| label: cox_workflow_function
#| echo: true

run_cox_workflow <- function(data,
                             time_var,
                             status_var,
                             p_cutoff = p_value_threshold) {

  outcome_cols <- c(time_var, 
                    status_var)

  all_features <- setdiff(colnames(data),
                          c(outcome_cols, 
                            "patient_id", 
                            "sample_id"))

  # Regularized Cox model
  x <- data |>
    select(all_of(all_features)) |>
    model.matrix(~ . -1, data = _)

  y <- Surv(data[[time_var]],
            data[[status_var]])

  if (regularization) {

    cvfit <- cv.glmnet(x,
                       y,
                       family = "cox",
                       type.measure = "C",
                       alpha = alpha)

    lambda_opt <- cvfit$lambda.min

    betas <- coef(cvfit, 
                  s = lambda_opt)

    beta_vec <- as.numeric(betas)

    selected_features <- rownames(betas)[beta_vec != 0]

  } else {
    selected_features <- colnames(x)
  }

  # Univariate Cox models
  if (length(selected_features) == 0) {
    return(NA)
  }

  univ_results <- map_dfr(
    selected_features,
    function(var) {

      formula <- as.formula(
        paste0(
          "Surv(", time_var, ", ", status_var, ") ~ ",
          var
        )
      )

      fit <- coxph(formula, 
                   data = data)
      
      fit <- summary(fit)

      tibble(variable = var,
             p_value  = fit$wald["pvalue"])
    }
  )

  if (nrow(univ_results) == 0) {
    return(NA)
  }

  significant_vars <- univ_results |>
    arrange(p_value) |>
    filter(p_value < p_cutoff) |>
    pull(variable)

  if (length(significant_vars) == 0) {
    return(NA)
  }

  # Multivariate Cox model
  formula <- as.formula(
    paste0(
      "Surv(", time_var, ", ", status_var, ") ~ ",
      paste(significant_vars, collapse = " + ")
    )
  )

  model <- coxph(formula, 
                 data = data)
  
  return(model)
}
```

# Predicting OS

## All features

```{r}
#| label: predict_os
#| echo: true
#| warning: false

results_os <- imap(
  folds_os,
  ~ {
    fold_idx <- .x
    fold_num <- .y

    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data_os)), 
                         fold_idx)
    train_data <- data_os[train_idx, ]
    test_data  <- data_os[fold_idx, ]

    # Fit model
    fit <- run_cox_workflow(train_data,
                            "years_to_os_event",
                            "os_status")

    if (is.na(fit)[1]) return(NULL)

    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred

    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )

    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance

    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }

    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)

    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )

    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_num,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )

    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_os <- map_dfr(results_os, "predictions") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "all")

predictions_os

write_tsv(predictions_os,
          file = "../results/05_cox_predictions.tsv",
          append = TRUE)

metrics_os <- map_dfr(results_os, "metrics") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "all")

metrics_os

write_tsv(metrics_os,
          file = "../results/05_cox_results.tsv",
          append = TRUE)


coefficients_os <- map_dfr(results_os, "coefficients") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "all")

coefficients_os

write_tsv(coefficients_os,
          file = "../results/05_cox_coefs.tsv",
          append = TRUE)
```

## No NLP data

```{r}
#| label: predict_os_noNLP
#| echo: true
#| warning: false

results_os_noNLP <- imap(
  folds_os_noNLP,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data_os_noNLP)), 
                         fold_idx)
    train_data <- data_os_noNLP[train_idx, ]
    test_data  <- data_os_noNLP[fold_idx, ]
    
    # Fit model
    fit <- run_cox_workflow(train_data,
                            "years_to_os_event",
                            "os_status")
    
    if (is.na(fit)[1]) return(NULL)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_num,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_os_noNLP <- map_dfr(results_os_noNLP, "predictions") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "noNLP")

predictions_os_noNLP

write_tsv(predictions_os_noNLP,
          file = "../results/05_cox_predictions.tsv",
          append = TRUE)

metrics_os_noNLP <- map_dfr(results_os_noNLP, "metrics") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "noNLP")

metrics_os_noNLP

write_tsv(metrics_os_noNLP,
          file = "../results/05_cox_results.tsv",
          append = TRUE)


coefficients_os_noNLP <- map_dfr(results_os_noNLP, "coefficients") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "noNLP")

coefficients_os_noNLP

write_tsv(coefficients_os_noNLP,
          file = "../results/05_cox_coefs.tsv",
          append = TRUE)
```

## No genomic data

```{r}
#| label: predict_os_nogenomic
#| echo: true
#| warning: false

results_os_nogenomic <- imap(
  folds_os_nogenomic,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data_os_nogenomic)), 
                         fold_idx)
    train_data <- data_os_nogenomic[train_idx, ]
    test_data  <- data_os_nogenomic[fold_idx, ]
    
    # Fit model
    fit <- run_cox_workflow(train_data,
                            "years_to_os_event",
                            "os_status")
    
    if (is.na(fit)[1]) return(NULL)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_num,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_os_nogenomic <- map_dfr(results_os_nogenomic, "predictions") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "nogenomic")

predictions_os_nogenomic

write_tsv(predictions_os_nogenomic,
          file = "../results/05_cox_predictions.tsv",
          append = TRUE)

metrics_os_nogenomic <- map_dfr(results_os_nogenomic, "metrics") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "nogenomic")

metrics_os_nogenomic

write_tsv(metrics_os_nogenomic,
          file = "../results/05_cox_results.tsv",
          append = TRUE)


coefficients_os_nogenomic <- map_dfr(results_os_nogenomic, "coefficients") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "nogenomic")

coefficients_os_nogenomic

write_tsv(coefficients_os_nogenomic,
          file = "../results/05_cox_coefs.tsv",
          append = TRUE)
```

## Only routine data

```{r}
#| label: predict_os_noNLPgenomic
#| echo: true
#| warning: false

results_os_noNLPgenomic <- imap(
  folds_os_noNLPgenomic,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data_os_noNLPgenomic)), 
                         fold_idx)
    train_data <- data_os_noNLPgenomic[train_idx, ]
    test_data  <- data_os_noNLPgenomic[fold_idx, ]
    
    # Fit model
    fit <- run_cox_workflow(train_data,
                            "years_to_os_event",
                            "os_status")
    
    if (is.na(fit)[1]) return(NULL)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_num,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_os_noNLPgenomic <- map_dfr(results_os_noNLPgenomic, "predictions") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "noNLPgenomic")

predictions_os_noNLPgenomic

write_tsv(predictions_os_noNLPgenomic,
          file = "../results/05_cox_predictions.tsv",
          append = TRUE)

metrics_os_noNLPgenomic <- map_dfr(results_os_noNLPgenomic, "metrics") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "noNLPgenomic")

metrics_os_noNLPgenomic

write_tsv(metrics_os_noNLPgenomic,
          file = "../results/05_cox_results.tsv",
          append = TRUE)


coefficients_os_noNLPgenomic <- map_dfr(results_os_noNLPgenomic, "coefficients") |> 
  mutate(model = setting,
         outcome = "OS",
         features = "noNLPgenomic")

coefficients_os_noNLPgenomic

write_tsv(coefficients_os_noNLPgenomic,
          file = "../results/05_cox_coefs.tsv",
          append = TRUE)
```

# Predicting DFS

## All features

```{r}
#| label: predict_dfs
#| echo: true
#| warning: false

results_dfs <- imap(
  folds_dfs,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data_dfs)), 
                         fold_idx)
    train_data <- data_dfs[train_idx, ]
    test_data  <- data_dfs[fold_idx, ]
    
    # Fit model
    fit <- run_cox_workflow(train_data,
                            "years_to_dfs_event",
                            "dfs_status")
    
    if (is.na(fit)[1]) return(NULL)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_num,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_dfs <- map_dfr(results_dfs, "predictions") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "all")

predictions_dfs

write_tsv(predictions_dfs,
          file = "../results/05_cox_predictions.tsv",
          append = TRUE)

metrics_dfs <- map_dfr(results_dfs, "metrics") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "all")

metrics_dfs

write_tsv(metrics_dfs,
          file = "../results/05_cox_results.tsv",
          append = TRUE)


coefficients_dfs <- map_dfr(results_dfs, "coefficients") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "all")

coefficients_dfs

write_tsv(coefficients_dfs,
          file = "../results/05_cox_coefs.tsv",
          append = TRUE)
```

## No NLP data

```{r}
#| label: predict_dfs_noNLP
#| echo: true
#| warning: false

results_dfs_noNLP <- imap(
  folds_dfs_noNLP,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data_dfs_noNLP)), 
                         fold_idx)
    train_data <- data_dfs_noNLP[train_idx, ]
    test_data  <- data_dfs_noNLP[fold_idx, ]
    
    # Fit model
    fit <- run_cox_workflow(train_data,
                            "years_to_dfs_event",
                            "dfs_status")
    
    if (is.na(fit)[1]) return(NULL)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_num,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_dfs_noNLP <- map_dfr(results_dfs_noNLP, "predictions") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "noNLP")

predictions_dfs_noNLP

write_tsv(predictions_dfs_noNLP,
          file = "../results/05_cox_predictions.tsv",
          append = TRUE)

metrics_dfs_noNLP <- map_dfr(results_dfs_noNLP, "metrics") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "noNLP")

metrics_dfs_noNLP

write_tsv(metrics_dfs_noNLP,
          file = "../results/05_cox_results.tsv",
          append = TRUE)


coefficients_dfs_noNLP <- map_dfr(results_dfs_noNLP, "coefficients") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "noNLP")

coefficients_dfs_noNLP

write_tsv(coefficients_dfs_noNLP,
          file = "../results/05_cox_coefs.tsv",
          append = TRUE)
```

## No genomic data

```{r}
#| label: predict_dfs_nogenomic
#| echo: true
#| warning: false

results_dfs_nogenomic <- imap(
  folds_dfs_nogenomic,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data_dfs_nogenomic)), 
                         fold_idx)
    train_data <- data_dfs_nogenomic[train_idx, ]
    test_data  <- data_dfs_nogenomic[fold_idx, ]
    
    # Fit model
    fit <- run_cox_workflow(train_data,
                            "years_to_dfs_event",
                            "dfs_status")
    
    if (is.na(fit)[1]) return(NULL)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_num,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_dfs_nogenomic <- map_dfr(results_dfs_nogenomic, "predictions") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "nogenomic")

predictions_dfs_nogenomic

write_tsv(predictions_dfs_nogenomic,
          file = "../results/05_cox_predictions.tsv",
          append = TRUE)

metrics_dfs_nogenomic <- map_dfr(results_dfs_nogenomic, "metrics") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "nogenomic")

metrics_dfs_nogenomic

write_tsv(metrics_dfs_nogenomic,
          file = "../results/05_cox_results.tsv",
          append = TRUE)


coefficients_dfs_nogenomic <- map_dfr(results_dfs_nogenomic, "coefficients") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "nogenomic")

coefficients_dfs_nogenomic

write_tsv(coefficients_dfs_nogenomic,
          file = "../results/05_cox_coefs.tsv",
          append = TRUE)
```

## Only routine data

```{r}
#| label: predict_dfs_noNLPgenomic
#| echo: true
#| warning: false

results_dfs_noNLPgenomic <- imap(
  folds_dfs_noNLPgenomic,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data_dfs_noNLPgenomic)), 
                         fold_idx)
    train_data <- data_dfs_noNLPgenomic[train_idx, ]
    test_data  <- data_dfs_noNLPgenomic[fold_idx, ]
    
    # Fit model
    fit <- run_cox_workflow(train_data,
                            "years_to_dfs_event",
                            "dfs_status")
    
    if (is.na(fit)[1]) return(NULL)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_num,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_dfs_noNLPgenomic <- map_dfr(results_dfs_noNLPgenomic, "predictions") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "noNLPgenomic")

predictions_dfs_noNLPgenomic

write_tsv(predictions_dfs_noNLPgenomic,
          file = "../results/05_cox_predictions.tsv",
          append = TRUE)

metrics_dfs_noNLPgenomic <- map_dfr(results_dfs_noNLPgenomic, "metrics") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "noNLPgenomic")

metrics_dfs_noNLPgenomic

write_tsv(metrics_dfs_noNLPgenomic,
          file = "../results/05_cox_results.tsv",
          append = TRUE)


coefficients_dfs_noNLPgenomic <- map_dfr(results_dfs_noNLPgenomic, "coefficients") |> 
  mutate(model = setting,
         outcome = "DFS",
         features = "noNLPgenomic")

coefficients_dfs_noNLPgenomic

write_tsv(coefficients_dfs_noNLPgenomic,
          file = "../results/05_cox_coefs.tsv",
          append = TRUE)
```
