---
title: "Stepwise Cox models"
author: "Puck Quarles van Ufford"
date: today
format: html
---

# Set up

```{r}
#| label: packages
#| message: false
#| echo: true

library("tidyverse")
library("survival")
library("caret")
library("purrr")
library("pROC")
```

```{r}
#| label: seed
#| echo: true

set.seed(8)
```

# Load data

```{r}
#| label: load_data
#| message: false
#| echo: true

data_os <- read_tsv(file = "../data/03_data_train_os.tsv")
data_os_noNLP <- read_tsv(file = "../data/03_data_train_os_noNLP.tsv")
data_os_nogenomic <- read_tsv(file = "../data/03_data_train_os_nogenomic.tsv")
data_os_noNLPgenomic <- read_tsv(file = "../data/03_data_train_os_noNLPgenomic.tsv")

data_dfs <- read_tsv(file = "../data/03_data_train_dfs.tsv")
data_dfs_noNLP <- read_tsv(file = "../data/03_data_train_dfs_noNLP.tsv")
data_dfs_nogenomic <- read_tsv(file = "../data/03_data_train_dfs_nogenomic.tsv")
data_dfs_noNLPgenomic <- read_tsv(file = "../data/03_data_train_dfs_noNLPgenomic.tsv")
```

# Settings

```{r}
#| label: settings
#| echo: true

max_iterations <- 10
```

# Set up cross-validation

```{r}
#| label: 5_fold_CV
#| echo: true

folds_os <- createFolds(data_os$os_status,
                        k = 5,
                        list = TRUE,
                        returnTrain = FALSE)
folds_os_noNLP <- createFolds(data_os_noNLP$os_status,
                              k = 5,
                              list = TRUE,
                              returnTrain = FALSE)
folds_os_nogenomic <- createFolds(data_os_nogenomic$os_status,
                                  k = 5,
                                  list = TRUE,
                                  returnTrain = FALSE)
folds_os_noNLPgenomic <- createFolds(data_os_noNLPgenomic$os_status,
                                     k = 5,
                                     list = TRUE,
                                     returnTrain = FALSE)

folds_dfs <- createFolds(data_dfs$dfs_status,
                         k = 5,
                         list = TRUE,
                         returnTrain = FALSE)
folds_dfs_noNLP <- createFolds(data_dfs_noNLP$dfs_status,
                               k = 5,
                               list = TRUE,
                               returnTrain = FALSE)
folds_dfs_nogenomic <- createFolds(data_dfs_nogenomic$dfs_status,
                                   k = 5,
                                   list = TRUE,
                                   returnTrain = FALSE)
folds_dfs_noNLPgenomic <- createFolds(data_dfs_noNLPgenomic$dfs_status,
                                      k = 5,
                                      list = TRUE,
                                      returnTrain = FALSE)
```

# Forward stepwise Cox model workflow

```{r}
#| label: forward_stepwise_Cox_function
#| echo: true

forward_cox_cv <- function(data, 
                           time_var,
                           status_var, 
                           folds, 
                           max_iter = max_iterations) {

  outcome_cols <- c(time_var, 
                    status_var)
  
  all_features <- setdiff(colnames(data),
                          c(outcome_cols, 
                            "patient_id", 
                            "sample_id"))

  results <- list()

  for (k in seq_along(folds)) {

    test_idx  <- folds[[k]]
    train_idx <- setdiff(seq_len(nrow(data)),
                         test_idx)

    data_train <- data[train_idx, ]
    data_test  <- data[test_idx, ]

    features_to_test <- all_features
    added_features <- character()

    max_iter_k <- min(length(all_features), 
                      max_iter)

    for (iter in seq_len(max_iter_k)) {

      c_indices <- tibble(feature = character(),
                          c_index = numeric())

      for (f in features_to_test) {

        formula <- as.formula(paste0(
          "Surv(", time_var, ", ", status_var,  ") ~ ",
          paste(c(added_features,
                  f), 
                collapse = " + ")))

        model <- coxph(formula, 
                       data = data_train)

        c_index <- summary(model)$concordance[1]

        c_indices <- add_row(c_indices,
                             feature = f,
                             c_index = c_index)
      }

      best_feature <- c_indices$feature[which.max(c_indices$c_index)]
      
      formula <- as.formula(paste0(
        "Surv(", time_var, ", ", status_var,  ") ~ ",
        paste(c(added_features,
                best_feature), 
              collapse = " + ")))
      
      model <- coxph(formula,
                     data = data_train)
      
      prediction <- predict(model,
                            newdata = data_test, 
                            type = "lp")
      
      c_index <- survConcordance(as.formula(paste0(
        "Surv(", time_var, ", ", status_var, ") ~ prediction")),
        data = data_test)$concordance

      results[[length(results) + 1]] <- tibble(
        fold = k,
        iteration = iter,
        added_feature = best_feature,
        c_index = c_index)

      added_features <- c(added_features, 
                          best_feature)
      
      features_to_test <- setdiff(features_to_test, 
                                  best_feature)
    }
  }

  bind_rows(results)
}
```

# Predicting OS

## All features

```{r}
#| label: predict_os
#| echo: true
#| warning: false

results_os <- forward_cox_cv(
  data = data_os,
  time_var = "years_to_os_event",
  status_var = "os_status",
  folds = folds_os
)

restuls_all_iterations_os <- results_os |> 
  mutate(
    model = "stepwise",
    outcome = "OS",
    features = "all"
  )

restuls_all_iterations_os

write_tsv(restuls_all_iterations_os,
          file = paste0("../results/06_res_all_iterations_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

results_os |> 
  group_by(iteration) |> 
  summarise(
    mean_c_index = mean(c_index),
    lower_95 = quantile(c_index, 0.025),
    upper_95 = quantile(c_index, 0.975),
    .groups = "drop"
  ) |> 
  ggplot(aes(x = iteration,
             y = mean_c_index)) +
  geom_line() +
  geom_ribbon(
    aes(ymin = lower_95,
        ymax = upper_95),
    alpha = 0.2
  ) +
  labs(
    x = "Number of features included",
    y = "C-index (95% CI)",
    title = "Forward stepwise Cox model (OS)",
    subtitle = "Feature sets included: all"
  ) +
  theme_bw()

ggsave(paste0("../results/06_C_index_plot_OS_",
              as.character(max_iterations),
              "_max.png"))

feature_paths <- results_os |> 
  arrange(fold, 
          iteration) |> 
  group_by(fold) |> 
  summarise(
    iteration = iteration,
    feature_set = purrr::accumulate(
      added_feature,
      ~ c(.x, .y)
    ),
    .groups = "drop"
  )

best_iter <- results_os |> 
  group_by(fold) |> 
  slice_max(
    c_index,
    n = 1,
    with_ties = FALSE
  ) |> 
  select(fold, 
         iteration)

best_models <- best_iter |> 
  left_join(feature_paths, by = c("fold", "iteration"))

best_models

final_models_os <- map(
  seq_len(nrow(best_models)),
  function(i) {

    fold_name <- best_models$fold[i]
    fold_idx  <- as.integer(gsub("Fold", "", fold_name))
    selected_features <- best_models$feature_set[[i]]

    # Split train / test
    test_idx  <- folds_os[[fold_idx]]
    train_idx <- setdiff(seq_len(nrow(data_os)), 
                         test_idx)

    train_data <- data_os[train_idx, ]
    test_data  <- data_os[test_idx, ]

    # Fit final model
    formula <- as.formula(paste0(
      "Surv(years_to_os_event, os_status) ~ ",
      paste(selected_features, collapse = " + ")
    ))

    fit <- coxph(formula, 
                 data = train_data)

    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred

    predictions <- tibble(
      fold = fold_name,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )

    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance

    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(
            status_t[keep],
            risk[keep],
            quiet = TRUE)$auc
        )
      }
    }

    metrics <- tibble(
      fold = fold_name,
      c_index = c_index,
      auc_12_months = compute_auc(1),
      auc_18_months = compute_auc(1.5),
      auc_24_months = compute_auc(2),
      auc_36_months = compute_auc(3)
    )

    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_name,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_os <- map_dfr(final_models_os, "predictions") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

predictions_os

write_tsv(predictions_os,
          file = paste0("../results/06_predictions_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

metrics_os <- map_dfr(final_models_os, "metrics") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

metrics_os

write_tsv(metrics_os,
          file = paste0("../results/06_results_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

coefficients_os <- map_dfr(final_models_os, "coefficients") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

coefficients_os

write_tsv(coefficients_os,
          file = paste0("../results/06_coefs_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)
```

## No NLP data

```{r}
#| label: predict_os_noNLP
#| echo: true
#| warning: false

results_os_noNLP <- forward_cox_cv(
  data = data_os_noNLP,
  time_var = "years_to_os_event",
  status_var = "os_status",
  folds = folds_os_noNLP
)

restuls_all_iterations_os_noNLP <- results_os_noNLP |> 
  mutate(
    model = "stepwise",
    outcome = "OS",
    features = "all"
  )

restuls_all_iterations_os_noNLP

write_tsv(restuls_all_iterations_os_noNLP,
          file = paste0("../results/06_res_all_iterations_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

results_os_noNLP |> 
  group_by(iteration) |> 
  summarise(
    mean_c_index = mean(c_index),
    lower_95 = quantile(c_index, 0.025),
    upper_95 = quantile(c_index, 0.975),
    .groups = "drop"
  ) |> 
  ggplot(aes(x = iteration,
             y = mean_c_index)) +
  geom_line() +
  geom_ribbon(
    aes(ymin = lower_95,
        ymax = upper_95),
    alpha = 0.2
  ) +
  labs(
    x = "Number of features included",
    y = "C-index (95% CI)",
    title = "Forward stepwise Cox model (OS)",
    subtitle = "Feature sets included: no NLP"
  ) +
  theme_bw()

ggsave(paste0("../results/06_C_index_plot_OS_noNLP_",
              as.character(max_iterations),
              "_max.png"))

feature_paths <- results_os_noNLP |> 
  arrange(fold, 
          iteration) |> 
  group_by(fold) |> 
  summarise(
    iteration = iteration,
    feature_set = purrr::accumulate(
      added_feature,
      ~ c(.x, .y)
    ),
    .groups = "drop"
  )

best_iter <- results_os_noNLP |> 
  group_by(fold) |> 
  slice_max(
    c_index,
    n = 1,
    with_ties = FALSE
  ) |> 
  select(fold, 
         iteration)

best_models <- best_iter |> 
  left_join(feature_paths, by = c("fold", "iteration"))

best_models

final_models_os_noNLP <- map(
  seq_len(nrow(best_models)),
  function(i) {
    
    fold_name <- best_models$fold[i]
    fold_idx  <- as.integer(gsub("Fold", "", fold_name))
    selected_features <- best_models$feature_set[[i]]
    
    # Split train / test
    test_idx  <- folds_os_noNLP[[fold_idx]]
    train_idx <- setdiff(seq_len(nrow(data_os_noNLP)), 
                         test_idx)
    
    train_data <- data_os_noNLP[train_idx, ]
    test_data  <- data_os_noNLP[test_idx, ]
    
    # Fit final model
    formula <- as.formula(paste0(
      "Surv(years_to_os_event, os_status) ~ ",
      paste(selected_features, collapse = " + ")
    ))
    
    fit <- coxph(formula, 
                 data = train_data)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_name,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(
            status_t[keep],
            risk[keep],
            quiet = TRUE)$auc
        )
      }
    }
    
    metrics <- tibble(
      fold = fold_name,
      c_index = c_index,
      auc_12_months = compute_auc(1),
      auc_18_months = compute_auc(1.5),
      auc_24_months = compute_auc(2),
      auc_36_months = compute_auc(3)
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_name,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_os_noNLP <- map_dfr(final_models_os_noNLP, "predictions") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

predictions_os_noNLP

write_tsv(predictions_os_noNLP,
          file = paste0("../results/06_predictions_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

metrics_os_noNLP <- map_dfr(final_models_os_noNLP, "metrics") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

metrics_os_noNLP

write_tsv(metrics_os_noNLP,
          file = paste0("../results/06_results_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

coefficients_os_noNLP <- map_dfr(final_models_os_noNLP, "coefficients") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

coefficients_os_noNLP

write_tsv(coefficients_os_noNLP,
          file = paste0("../results/06_coefs_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)
```

## No genomic data

```{r}
#| label: predict_os_nogenomic
#| echo: true
#| warning: false

results_os_nogenomic <- forward_cox_cv(
  data = data_os_nogenomic,
  time_var = "years_to_os_event",
  status_var = "os_status",
  folds = folds_os_nogenomic
)

restuls_all_iterations_os_nogenomic <- results_os_nogenomic |> 
  mutate(
    model = "stepwise",
    outcome = "OS",
    features = "all"
  )

restuls_all_iterations_os_nogenomic

write_tsv(restuls_all_iterations_os_nogenomic,
          file = paste0("../results/06_res_all_iterations_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

results_os_nogenomic |> 
  group_by(iteration) |> 
  summarise(
    mean_c_index = mean(c_index),
    lower_95 = quantile(c_index, 0.025),
    upper_95 = quantile(c_index, 0.975),
    .groups = "drop"
  ) |> 
  ggplot(aes(x = iteration,
             y = mean_c_index)) +
  geom_line() +
  geom_ribbon(
    aes(ymin = lower_95,
        ymax = upper_95),
    alpha = 0.2
  ) +
  labs(
    x = "Number of features included",
    y = "C-index (95% CI)",
    title = "Forward stepwise Cox model (OS)",
    subtitle = "Feature sets included: no genomic"
  ) +
  theme_bw()

ggsave(paste0("../results/06_C_index_plot_OS_nogenomic_",
              as.character(max_iterations),
              "_max.png"))

feature_paths <- results_os_nogenomic |> 
  arrange(fold, 
          iteration) |> 
  group_by(fold) |> 
  summarise(
    iteration = iteration,
    feature_set = purrr::accumulate(
      added_feature,
      ~ c(.x, .y)
    ),
    .groups = "drop"
  )

best_iter <- results_os_nogenomic |> 
  group_by(fold) |> 
  slice_max(
    c_index,
    n = 1,
    with_ties = FALSE
  ) |> 
  select(fold, 
         iteration)

best_models <- best_iter |> 
  left_join(feature_paths, by = c("fold", "iteration"))

best_models

final_models_os_nogenomic <- map(
  seq_len(nrow(best_models)),
  function(i) {
    
    fold_name <- best_models$fold[i]
    fold_idx  <- as.integer(gsub("Fold", "", fold_name))
    selected_features <- best_models$feature_set[[i]]
    
    # Split train / test
    test_idx  <- folds_os_nogenomic[[fold_idx]]
    train_idx <- setdiff(seq_len(nrow(data_os_nogenomic)), 
                         test_idx)
    
    train_data <- data_os_nogenomic[train_idx, ]
    test_data  <- data_os_nogenomic[test_idx, ]
    
    # Fit final model
    formula <- as.formula(paste0(
      "Surv(years_to_os_event, os_status) ~ ",
      paste(selected_features, collapse = " + ")
    ))
    
    fit <- coxph(formula, 
                 data = train_data)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_name,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(
            status_t[keep],
            risk[keep],
            quiet = TRUE)$auc
        )
      }
    }
    
    metrics <- tibble(
      fold = fold_name,
      c_index = c_index,
      auc_12_months = compute_auc(1),
      auc_18_months = compute_auc(1.5),
      auc_24_months = compute_auc(2),
      auc_36_months = compute_auc(3)
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_name,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_os_nogenomic <- map_dfr(final_models_os_nogenomic, "predictions") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

predictions_os_nogenomic

write_tsv(predictions_os_nogenomic,
          file = paste0("../results/06_predictions_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

metrics_os_nogenomic <- map_dfr(final_models_os_nogenomic, "metrics") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

metrics_os_nogenomic

write_tsv(metrics_os_nogenomic,
          file = paste0("../results/06_results_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

coefficients_os_nogenomic <- map_dfr(final_models_os_nogenomic, "coefficients") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

coefficients_os_nogenomic

write_tsv(coefficients_os_nogenomic,
          file = paste0("../results/06_coefs_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)
```

## Only routine data

```{r}
#| label: predict_os_noNLPgenomic
#| echo: true
#| warning: false

results_os_noNLPgenomic <- forward_cox_cv(
  data = data_os_noNLPgenomic,
  time_var = "years_to_os_event",
  status_var = "os_status",
  folds = folds_os_noNLPgenomic
)

restuls_all_iterations_os_noNLPgenomic <- results_os_noNLPgenomic |> 
  mutate(
    model = "stepwise",
    outcome = "OS",
    features = "all"
  )

restuls_all_iterations_os_noNLPgenomic

write_tsv(restuls_all_iterations_os_noNLPgenomic,
          file = paste0("../results/06_res_all_iterations_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

results_os_noNLPgenomic |> 
  group_by(iteration) |> 
  summarise(
    mean_c_index = mean(c_index),
    lower_95 = quantile(c_index, 0.025),
    upper_95 = quantile(c_index, 0.975),
    .groups = "drop"
  ) |> 
  ggplot(aes(x = iteration,
             y = mean_c_index)) +
  geom_line() +
  geom_ribbon(
    aes(ymin = lower_95,
        ymax = upper_95),
    alpha = 0.2
  ) +
  labs(
    x = "Number of features included",
    y = "C-index (95% CI)",
    title = "Forward stepwise Cox model (OS)",
    subtitle = "Feature sets included: no NLP or genomic"
  ) +
  theme_bw()

ggsave(paste0("../results/06_C_index_plot_OS_noNLPgenomic_",
              as.character(max_iterations),
              "_max.png"))

feature_paths <- results_os_noNLPgenomic |> 
  arrange(fold, 
          iteration) |> 
  group_by(fold) |> 
  summarise(
    iteration = iteration,
    feature_set = purrr::accumulate(
      added_feature,
      ~ c(.x, .y)
    ),
    .groups = "drop"
  )

best_iter <- results_os_noNLPgenomic |> 
  group_by(fold) |> 
  slice_max(
    c_index,
    n = 1,
    with_ties = FALSE
  ) |> 
  select(fold, 
         iteration)

best_models <- best_iter |> 
  left_join(feature_paths, by = c("fold", "iteration"))

best_models

final_models_os_noNLPgenomic <- map(
  seq_len(nrow(best_models)),
  function(i) {
    
    fold_name <- best_models$fold[i]
    fold_idx  <- as.integer(gsub("Fold", "", fold_name))
    selected_features <- best_models$feature_set[[i]]
    
    # Split train / test
    test_idx  <- folds_os_noNLPgenomic[[fold_idx]]
    train_idx <- setdiff(seq_len(nrow(data_os_noNLPgenomic)), 
                         test_idx)
    
    train_data <- data_os_noNLPgenomic[train_idx, ]
    test_data  <- data_os_noNLPgenomic[test_idx, ]
    
    # Fit final model
    formula <- as.formula(paste0(
      "Surv(years_to_os_event, os_status) ~ ",
      paste(selected_features, collapse = " + ")
    ))
    
    fit <- coxph(formula, 
                 data = train_data)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_name,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(
            status_t[keep],
            risk[keep],
            quiet = TRUE)$auc
        )
      }
    }
    
    metrics <- tibble(
      fold = fold_name,
      c_index = c_index,
      auc_12_months = compute_auc(1),
      auc_18_months = compute_auc(1.5),
      auc_24_months = compute_auc(2),
      auc_36_months = compute_auc(3)
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_name,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_os_noNLPgenomic <- map_dfr(final_models_os_noNLPgenomic, "predictions") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

predictions_os_noNLPgenomic

write_tsv(predictions_os_noNLPgenomic,
          file = paste0("../results/06_predictions_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

metrics_os_noNLPgenomic <- map_dfr(final_models_os_noNLPgenomic, "metrics") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

metrics_os_noNLPgenomic

write_tsv(metrics_os_noNLPgenomic,
          file = paste0("../results/06_results_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

coefficients_os_noNLPgenomic <- map_dfr(final_models_os_noNLPgenomic, "coefficients") |> 
  mutate(model = "stepwise",
         outcome = "OS",
         features = "all")

coefficients_os_noNLPgenomic

write_tsv(coefficients_os_noNLPgenomic,
          file = paste0("../results/06_coefs_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)
```

# Predicting DFS

S

## All features

```{r}
#| label: predict_dfs
#| echo: true
#| warning: false

results_dfs <- forward_cox_cv(
  data = data_dfs,
  time_var = "years_to_dfs_event",
  status_var = "dfs_status",
  folds = folds_dfs
)

restuls_all_iterations_dfs <- results_dfs |> 
  mutate(
    model = "stepwise",
    outcome = "DFS",
    features = "all"
  )

restuls_all_iterations_dfs

write_tsv(restuls_all_iterations_dfs,
          file = paste0("../results/06_res_all_iterations_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

results_dfs |> 
  group_by(iteration) |> 
  summarise(
    mean_c_index = mean(c_index),
    lower_95 = quantile(c_index, 0.025),
    upper_95 = quantile(c_index, 0.975),
    .groups = "drop"
  ) |> 
  ggplot(aes(x = iteration,
             y = mean_c_index)) +
  geom_line() +
  geom_ribbon(
    aes(ymin = lower_95,
        ymax = upper_95),
    alpha = 0.2
  ) +
  labs(
    x = "Number of features included",
    y = "C-index (95% CI)",
    title = "Forward stepwise Cox model (DFS)",
    subtitle = "Feature sets included: all"
  ) +
  theme_bw()

ggsave(paste0("../results/06_C_index_plot_DFS_",
              as.character(max_iterations),
              "_max.png"))

feature_paths <- results_dfs |> 
  arrange(fold, 
          iteration) |> 
  group_by(fold) |> 
  summarise(
    iteration = iteration,
    feature_set = purrr::accumulate(
      added_feature,
      ~ c(.x, .y)
    ),
    .groups = "drop"
  )

best_iter <- results_dfs |> 
  group_by(fold) |> 
  slice_max(
    c_index,
    n = 1,
    with_ties = FALSE
  ) |> 
  select(fold, 
         iteration)

best_models <- best_iter |> 
  left_join(feature_paths, by = c("fold", "iteration"))

best_models

final_models_dfs <- map(
  seq_len(nrow(best_models)),
  function(i) {
    
    fold_name <- best_models$fold[i]
    fold_idx  <- as.integer(gsub("Fold", "", fold_name))
    selected_features <- best_models$feature_set[[i]]
    
    # Split train / test
    test_idx  <- folds_dfs[[fold_idx]]
    train_idx <- setdiff(seq_len(nrow(data_dfs)), 
                         test_idx)
    
    train_data <- data_dfs[train_idx, ]
    test_data  <- data_dfs[test_idx, ]
    
    # Fit final model
    formula <- as.formula(paste0(
      "Surv(years_to_dfs_event, dfs_status) ~ ",
      paste(selected_features, collapse = " + ")
    ))
    
    fit <- coxph(formula, 
                 data = train_data)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_name,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(
            status_t[keep],
            risk[keep],
            quiet = TRUE)$auc
        )
      }
    }
    
    metrics <- tibble(
      fold = fold_name,
      c_index = c_index,
      auc_12_months = compute_auc(1),
      auc_18_months = compute_auc(1.5),
      auc_24_months = compute_auc(2),
      auc_36_months = compute_auc(3)
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_name,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_dfs <- map_dfr(final_models_dfs, "predictions") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

predictions_dfs

write_tsv(predictions_dfs,
          file = paste0("../results/06_predictions_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

metrics_dfs <- map_dfr(final_models_dfs, "metrics") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

metrics_dfs

write_tsv(metrics_dfs,
          file = paste0("../results/06_results_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

coefficients_dfs <- map_dfr(final_models_dfs, "coefficients") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

coefficients_dfs

write_tsv(coefficients_dfs,
          file = paste0("../results/06_coefs_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)
```

## No NLP data

```{r}
#| label: predict_dfs_noNLP
#| echo: true
#| warning: false

results_dfs_noNLP <- forward_cox_cv(
  data = data_dfs_noNLP,
  time_var = "years_to_dfs_event",
  status_var = "dfs_status",
  folds = folds_dfs_noNLP
)

restuls_all_iterations_dfs_noNLP <- results_dfs_noNLP |> 
  mutate(
    model = "stepwise",
    outcome = "DFS",
    features = "all"
  )

restuls_all_iterations_dfs_noNLP

write_tsv(restuls_all_iterations_dfs_noNLP,
          file = paste0("../results/06_res_all_iterations_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

results_dfs_noNLP |> 
  group_by(iteration) |> 
  summarise(
    mean_c_index = mean(c_index),
    lower_95 = quantile(c_index, 0.025),
    upper_95 = quantile(c_index, 0.975),
    .groups = "drop"
  ) |> 
  ggplot(aes(x = iteration,
             y = mean_c_index)) +
  geom_line() +
  geom_ribbon(
    aes(ymin = lower_95,
        ymax = upper_95),
    alpha = 0.2
  ) +
  labs(
    x = "Number of features included",
    y = "C-index (95% CI)",
    title = "Forward stepwise Cox model (DFS)",
    subtitle = "Feature sets included: no NLP"
  ) +
  theme_bw()

ggsave(paste0("../results/06_C_index_plot_DFS_noNLP_",
              as.character(max_iterations),
              "_max.png"))

feature_paths <- results_dfs_noNLP |> 
  arrange(fold, 
          iteration) |> 
  group_by(fold) |> 
  summarise(
    iteration = iteration,
    feature_set = purrr::accumulate(
      added_feature,
      ~ c(.x, .y)
    ),
    .groups = "drop"
  )

best_iter <- results_dfs_noNLP |> 
  group_by(fold) |> 
  slice_max(
    c_index,
    n = 1,
    with_ties = FALSE
  ) |> 
  select(fold, 
         iteration)

best_models <- best_iter |> 
  left_join(feature_paths, by = c("fold", "iteration"))

best_models

final_models_dfs_noNLP <- map(
  seq_len(nrow(best_models)),
  function(i) {
    
    fold_name <- best_models$fold[i]
    fold_idx  <- as.integer(gsub("Fold", "", fold_name))
    selected_features <- best_models$feature_set[[i]]
    
    # Split train / test
    test_idx  <- folds_dfs_noNLP[[fold_idx]]
    train_idx <- setdiff(seq_len(nrow(data_dfs_noNLP)), 
                         test_idx)
    
    train_data <- data_dfs_noNLP[train_idx, ]
    test_data  <- data_dfs_noNLP[test_idx, ]
    
    # Fit final model
    formula <- as.formula(paste0(
      "Surv(years_to_dfs_event, dfs_status) ~ ",
      paste(selected_features, collapse = " + ")
    ))
    
    fit <- coxph(formula, 
                 data = train_data)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_name,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(
            status_t[keep],
            risk[keep],
            quiet = TRUE)$auc
        )
      }
    }
    
    metrics <- tibble(
      fold = fold_name,
      c_index = c_index,
      auc_12_months = compute_auc(1),
      auc_18_months = compute_auc(1.5),
      auc_24_months = compute_auc(2),
      auc_36_months = compute_auc(3)
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_name,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_dfs_noNLP <- map_dfr(final_models_dfs_noNLP, "predictions") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

predictions_dfs_noNLP

write_tsv(predictions_dfs_noNLP,
          file = paste0("../results/06_predictions_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

metrics_dfs_noNLP <- map_dfr(final_models_dfs_noNLP, "metrics") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

metrics_dfs_noNLP

write_tsv(metrics_dfs_noNLP,
          file = paste0("../results/06_results_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

coefficients_dfs_noNLP <- map_dfr(final_models_dfs_noNLP, "coefficients") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

coefficients_dfs_noNLP

write_tsv(coefficients_dfs_noNLP,
          file = paste0("../results/06_coefs_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)
```

## No genomic data

```{r}
#| label: predict_dfs_nogenomic
#| echo: true
#| warning: false

results_dfs_nogenomic <- forward_cox_cv(
  data = data_dfs_nogenomic,
  time_var = "years_to_dfs_event",
  status_var = "dfs_status",
  folds = folds_dfs_nogenomic
)

restuls_all_iterations_dfs_nogenomic <- results_dfs_nogenomic |> 
  mutate(
    model = "stepwise",
    outcome = "DFS",
    features = "all"
  )

restuls_all_iterations_dfs_nogenomic

write_tsv(restuls_all_iterations_dfs_nogenomic,
          file = paste0("../results/06_res_all_iterations_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

results_dfs_nogenomic |> 
  group_by(iteration) |> 
  summarise(
    mean_c_index = mean(c_index),
    lower_95 = quantile(c_index, 0.025),
    upper_95 = quantile(c_index, 0.975),
    .groups = "drop"
  ) |> 
  ggplot(aes(x = iteration,
             y = mean_c_index)) +
  geom_line() +
  geom_ribbon(
    aes(ymin = lower_95,
        ymax = upper_95),
    alpha = 0.2
  ) +
  labs(
    x = "Number of features included",
    y = "C-index (95% CI)",
    title = "Forward stepwise Cox model (DFS)",
    subtitle = "Feature sets included: no genomic"
  ) +
  theme_bw()

ggsave(paste0("../results/06_C_index_plot_DFS_nogenomic_",
              as.character(max_iterations),
              "_max.png"))

feature_paths <- results_dfs_nogenomic |> 
  arrange(fold, 
          iteration) |> 
  group_by(fold) |> 
  summarise(
    iteration = iteration,
    feature_set = purrr::accumulate(
      added_feature,
      ~ c(.x, .y)
    ),
    .groups = "drop"
  )

best_iter <- results_dfs_nogenomic |> 
  group_by(fold) |> 
  slice_max(
    c_index,
    n = 1,
    with_ties = FALSE
  ) |> 
  select(fold, 
         iteration)

best_models <- best_iter |> 
  left_join(feature_paths, by = c("fold", "iteration"))

best_models

final_models_dfs_nogenomic <- map(
  seq_len(nrow(best_models)),
  function(i) {
    
    fold_name <- best_models$fold[i]
    fold_idx  <- as.integer(gsub("Fold", "", fold_name))
    selected_features <- best_models$feature_set[[i]]
    
    # Split train / test
    test_idx  <- folds_dfs_nogenomic[[fold_idx]]
    train_idx <- setdiff(seq_len(nrow(data_dfs_nogenomic)), 
                         test_idx)
    
    train_data <- data_dfs_nogenomic[train_idx, ]
    test_data  <- data_dfs_nogenomic[test_idx, ]
    
    # Fit final model
    formula <- as.formula(paste0(
      "Surv(years_to_dfs_event, dfs_status) ~ ",
      paste(selected_features, collapse = " + ")
    ))
    
    fit <- coxph(formula, 
                 data = train_data)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_name,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(
            status_t[keep],
            risk[keep],
            quiet = TRUE)$auc
        )
      }
    }
    
    metrics <- tibble(
      fold = fold_name,
      c_index = c_index,
      auc_12_months = compute_auc(1),
      auc_18_months = compute_auc(1.5),
      auc_24_months = compute_auc(2),
      auc_36_months = compute_auc(3)
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_name,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_dfs_nogenomic <- map_dfr(final_models_dfs_nogenomic, "predictions") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

predictions_dfs_nogenomic

write_tsv(predictions_dfs_nogenomic,
          file = paste0("../results/06_predictions_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

metrics_dfs_nogenomic <- map_dfr(final_models_dfs_nogenomic, "metrics") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

metrics_dfs_nogenomic

write_tsv(metrics_dfs_nogenomic,
          file = paste0("../results/06_results_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

coefficients_dfs_nogenomic <- map_dfr(final_models_dfs_nogenomic, "coefficients") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

coefficients_dfs_nogenomic

write_tsv(coefficients_dfs_nogenomic,
          file = paste0("../results/06_coefs_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)
```

## Only routine data

```{r}
#| label: predict_dfs_noNLPgenomic
#| echo: true
#| warning: false

results_dfs_noNLPgenomic <- forward_cox_cv(
  data = data_dfs_noNLPgenomic,
  time_var = "years_to_dfs_event",
  status_var = "dfs_status",
  folds = folds_dfs_noNLPgenomic
)

restuls_all_iterations_dfs_noNLPgenomic <- results_dfs_noNLPgenomic |> 
  mutate(
    model = "stepwise",
    outcome = "DFS",
    features = "all"
  )

restuls_all_iterations_dfs_noNLPgenomic

write_tsv(restuls_all_iterations_dfs_noNLPgenomic,
          file = paste0("../results/06_res_all_iterations_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

results_dfs_noNLPgenomic |> 
  group_by(iteration) |> 
  summarise(
    mean_c_index = mean(c_index),
    lower_95 = quantile(c_index, 0.025),
    upper_95 = quantile(c_index, 0.975),
    .groups = "drop"
  ) |> 
  ggplot(aes(x = iteration,
             y = mean_c_index)) +
  geom_line() +
  geom_ribbon(
    aes(ymin = lower_95,
        ymax = upper_95),
    alpha = 0.2
  ) +
  labs(
    x = "Number of features included",
    y = "C-index (95% CI)",
    title = "Forward stepwise Cox model (DFS)",
    subtitle = "Feature sets included: no NLP or genomic"
  ) +
  theme_bw()

ggsave(paste0("../results/06_C_index_plot_DFS_noNLPgenomic_",
              as.character(max_iterations),
              "_max.png"))

feature_paths <- results_dfs_noNLPgenomic |> 
  arrange(fold, 
          iteration) |> 
  group_by(fold) |> 
  summarise(
    iteration = iteration,
    feature_set = purrr::accumulate(
      added_feature,
      ~ c(.x, .y)
    ),
    .groups = "drop"
  )

best_iter <- results_dfs_noNLPgenomic |> 
  group_by(fold) |> 
  slice_max(
    c_index,
    n = 1,
    with_ties = FALSE
  ) |> 
  select(fold, 
         iteration)

best_models <- best_iter |> 
  left_join(feature_paths, by = c("fold", "iteration"))

best_models

final_models_dfs_noNLPgenomic <- map(
  seq_len(nrow(best_models)),
  function(i) {
    
    fold_name <- best_models$fold[i]
    fold_idx  <- as.integer(gsub("Fold", "", fold_name))
    selected_features <- best_models$feature_set[[i]]
    
    # Split train / test
    test_idx  <- folds_dfs_noNLPgenomic[[fold_idx]]
    train_idx <- setdiff(seq_len(nrow(data_dfs_noNLPgenomic)), 
                         test_idx)
    
    train_data <- data_dfs_noNLPgenomic[train_idx, ]
    test_data  <- data_dfs_noNLPgenomic[test_idx, ]
    
    # Fit final model
    formula <- as.formula(paste0(
      "Surv(years_to_dfs_event, dfs_status) ~ ",
      paste(selected_features, collapse = " + ")
    ))
    
    fit <- coxph(formula, 
                 data = train_data)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred
    
    predictions <- tibble(
      fold = fold_name,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(
            status_t[keep],
            risk[keep],
            quiet = TRUE)$auc
        )
      }
    }
    
    metrics <- tibble(
      fold = fold_name,
      c_index = c_index,
      auc_12_months = compute_auc(1),
      auc_18_months = compute_auc(1.5),
      auc_24_months = compute_auc(2),
      auc_36_months = compute_auc(3)
    )
    
    # Store coefficients
    coefs <- summary(fit)$coefficients
    coefs <- tibble(
      fold = fold_name,
      feature = rownames(coefs),
      beta = coefs[, "coef"],
      p_value = coefs[, "Pr(>|z|)"]
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      coefficients = coefs
    )
  }
)

predictions_dfs_noNLPgenomic <- map_dfr(final_models_dfs_noNLPgenomic, "predictions") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

predictions_dfs_noNLPgenomic

write_tsv(predictions_dfs_noNLPgenomic,
          file = paste0("../results/06_predictions_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

metrics_dfs_noNLPgenomic <- map_dfr(final_models_dfs_noNLPgenomic, "metrics") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

metrics_dfs_noNLPgenomic

write_tsv(metrics_dfs_noNLPgenomic,
          file = paste0("../results/06_results_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)

coefficients_dfs_noNLPgenomic <- map_dfr(final_models_dfs_noNLPgenomic, "coefficients") |> 
  mutate(model = "stepwise",
         outcome = "DFS",
         features = "all")

coefficients_dfs_noNLPgenomic

write_tsv(coefficients_dfs_noNLPgenomic,
          file = paste0("../results/06_coefs_",
                        as.character(max_iterations),
                        "_max.tsv"),
          append = TRUE)
```
