---
title: "Random survival forest models"
author: "Puck Quarles van Ufford"
date: today
format: html
---

# Set up

```{r}
#| label: packages
#| message: false
#| echo: true

library("tidyverse")
library("randomForestSRC")
library("caret")
library("survival")
library("pROC")
```

```{r}
#| label: seed
#| echo: true

set.seed(8)
```

# Load data

```{r}
#| label: load_data
#| message: false
#| echo: true

data_os <- read_tsv(file = "../data/03_data_train_os.tsv")
data_os_noNLP <- read_tsv(file = "../data/03_data_train_os_noNLP.tsv")
data_os_nogenomic <- read_tsv(file = "../data/03_data_train_os_nogenomic.tsv")
data_os_noNLPgenomic <- read_tsv(file = "../data/03_data_train_os_noNLPgenomic.tsv")

data_dfs <- read_tsv(file = "../data/03_data_train_dfs.tsv")
data_dfs_noNLP <- read_tsv(file = "../data/03_data_train_dfs_noNLP.tsv")
data_dfs_nogenomic <- read_tsv(file = "../data/03_data_train_dfs_nogenomic.tsv")
data_dfs_noNLPgenomic <- read_tsv(file = "../data/03_data_train_dfs_noNLPgenomic.tsv")
```

# Settings

```{r}
#| label: settings
#| echo: true

trees <- 1000

rule <- "logrank" # logrank (default), bs.gradient, or logrankscore

#tree_grid <- c(1, seq(50, trees, by = 50))
```

# Set up cross-validation

```{r}
#| label: 5_fold_CV
#| echo: true

folds_os <- createFolds(data_os$os_status,
                        k = 5,
                        list = TRUE,
                        returnTrain = FALSE)
folds_os_noNLP <- createFolds(data_os_noNLP$os_status,
                              k = 5,
                              list = TRUE,
                              returnTrain = FALSE)
folds_os_nogenomic <- createFolds(data_os_nogenomic$os_status,
                                  k = 5,
                                  list = TRUE,
                                  returnTrain = FALSE)
folds_os_noNLPgenomic <- createFolds(data_os_noNLPgenomic$os_status,
                                     k = 5,
                                     list = TRUE,
                                     returnTrain = FALSE)

folds_dfs <- createFolds(data_dfs$dfs_status,
                         k = 5,
                         list = TRUE,
                         returnTrain = FALSE)
folds_dfs_noNLP <- createFolds(data_dfs_noNLP$dfs_status,
                               k = 5,
                               list = TRUE,
                               returnTrain = FALSE)
folds_dfs_nogenomic <- createFolds(data_dfs_nogenomic$dfs_status,
                                   k = 5,
                                   list = TRUE,
                                   returnTrain = FALSE)
folds_dfs_noNLPgenomic <- createFolds(data_dfs_noNLPgenomic$dfs_status,
                                      k = 5,
                                      list = TRUE,
                                      returnTrain = FALSE)
```

# Predicting OS

## All features

```{r}
#| label: predict_os
#| echo: true
#| warning: false

results_os <- imap(
  folds_os,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    data <- data_os |> 
      select(-c(patient_id, sample_id))
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data)),
                         fold_idx)
    train_data <- data[train_idx, ]
    test_data  <- data[fold_idx, ]
    
    # Fit RSF
    fit <- rfsrc(Surv(years_to_os_event, 
                      os_status) ~ ., 
                 data = train_data,
                 ntree = trees,
                 splitrule = rule,
                 importance = TRUE)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred$predicted
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )

    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance


  # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }

    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store variable importance
    imp <- fit$importance
    
    importance <- tibble(
      fold = fold_num,
      feature = names(imp),
      importance = as.numeric(imp)
    )

    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      importance = importance
    )
  }
)

predictions_os <- map_dfr(results_os, "predictions") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "all")

predictions_os

write_tsv(predictions_os,
          file = "../results/07_rsf_predictions.tsv",
          append = TRUE)

metrics_os <- map_dfr(results_os, "metrics") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "all")

metrics_os

write_tsv(metrics_os,
          file = "../results/07_rsf_results.tsv",
          append = TRUE)


importance_os <- map_dfr(results_os, "importance") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "all")

importance_os

write_tsv(importance_os,
          file = "../results/07_rsf_vimp.tsv",
          append = TRUE)
```

## No NLP data

```{r}
#| label: predict_os_noNLP
#| echo: true
#| warning: false

results_os_noNLP <- imap(
  folds_os_noNLP,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    data <- data_os_noNLP |> 
      select(-c(patient_id, sample_id))
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data)),
                         fold_idx)
    train_data <- data[train_idx, ]
    test_data  <- data[fold_idx, ]
    
    # Fit RSF
    fit <- rfsrc(Surv(years_to_os_event, 
                      os_status) ~ ., 
                 data = train_data,
                 ntree = trees,
                 splitrule = rule,
                 importance = TRUE)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred$predicted
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance
    
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store variable importance
    imp <- fit$importance
    
    importance <- tibble(
      fold = fold_num,
      feature = names(imp),
      importance = as.numeric(imp)
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      importance = importance
    )
  }
)

predictions_os_noNLP <- map_dfr(results_os_noNLP, "predictions") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "noNLP")

predictions_os_noNLP

write_tsv(predictions_os_noNLP,
          file = "../results/07_rsf_predictions.tsv",
          append = TRUE)

metrics_os_noNLP <- map_dfr(results_os_noNLP, "metrics") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "noNLP")

metrics_os_noNLP

write_tsv(metrics_os_noNLP,
          file = "../results/07_rsf_results.tsv",
          append = TRUE)


importance_os_noNLP <- map_dfr(results_os_noNLP, "importance") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "noNLP")

importance_os_noNLP

write_tsv(importance_os_noNLP,
          file = "../results/07_rsf_vimp.tsv",
          append = TRUE)
```

## No genomic data

```{r}
#| label: predict_os_nogenomic
#| echo: true
#| warning: false

results_os_nogenomic <- imap(
  folds_os_nogenomic,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    data <- data_os_nogenomic |> 
      select(-c(patient_id, sample_id))
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data)),
                         fold_idx)
    train_data <- data[train_idx, ]
    test_data  <- data[fold_idx, ]
    
    # Fit RSF
    fit <- rfsrc(Surv(years_to_os_event, 
                      os_status) ~ ., 
                 data = train_data,
                 ntree = trees,
                 splitrule = rule,
                 importance = TRUE)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred$predicted
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance
    
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store variable importance
    imp <- fit$importance
    
    importance <- tibble(
      fold = fold_num,
      feature = names(imp),
      importance = as.numeric(imp)
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      importance = importance
    )
  }
)

predictions_os_nogenomic <- map_dfr(results_os_nogenomic, "predictions") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "nogenomic")

predictions_os_nogenomic

write_tsv(predictions_os_nogenomic,
          file = "../results/07_rsf_predictions.tsv",
          append = TRUE)

metrics_os_nogenomic <- map_dfr(results_os_nogenomic, "metrics") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "nogenomic")

metrics_os_nogenomic

write_tsv(metrics_os_nogenomic,
          file = "../results/07_rsf_results.tsv",
          append = TRUE)


importance_os_nogenomic <- map_dfr(results_os_nogenomic, "importance") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "nogenomic")

importance_os_nogenomic

write_tsv(importance_os_nogenomic,
          file = "../results/07_rsf_vimp.tsv",
          append = TRUE)
```

## Only routine data

```{r}
#| label: predict_os_noNLPgenomic
#| echo: true
#| warning: false

results_os_noNLPgenomic <- imap(
  folds_os_noNLPgenomic,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    data <- data_os_noNLPgenomic |> 
      select(-c(patient_id, sample_id))
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data)),
                         fold_idx)
    train_data <- data[train_idx, ]
    test_data  <- data[fold_idx, ]
    
    # Fit RSF
    fit <- rfsrc(Surv(years_to_os_event, 
                      os_status) ~ ., 
                 data = train_data,
                 ntree = trees,
                 splitrule = rule,
                 importance = TRUE)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred$predicted
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      os_status = test_data$os_status,
      years_to_os_event = test_data$years_to_os_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_os_event, 
           test_data$os_status) ~ risk
    )$concordance
    
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_os_event <= t & test_data$os_status == 1 ~ 1,
        test_data$years_to_os_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store variable importance
    imp <- fit$importance
    
    importance <- tibble(
      fold = fold_num,
      feature = names(imp),
      importance = as.numeric(imp)
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      importance = importance
    )
  }
)

predictions_os_noNLPgenomic <- map_dfr(results_os_noNLPgenomic, "predictions") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "noNLPgenomic")

predictions_os_noNLPgenomic

write_tsv(predictions_os_noNLPgenomic,
          file = "../results/07_rsf_predictions.tsv",
          append = TRUE)

metrics_os_noNLPgenomic <- map_dfr(results_os_noNLPgenomic, "metrics") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "noNLPgenomic")

metrics_os_noNLPgenomic

write_tsv(metrics_os_noNLPgenomic,
          file = "../results/07_rsf_results.tsv",
          append = TRUE)


importance_os_noNLPgenomic <- map_dfr(results_os_noNLPgenomic, "importance") |> 
  mutate(model = "RSF",
         outcome = "OS",
         features = "noNLPgenomic")

importance_os_noNLPgenomic

write_tsv(importance_os_noNLPgenomic,
          file = "../results/07_rsf_vimp.tsv",
          append = TRUE)
```

# Predicting DFS

## All features

```{r}
#| label: predict_dfs
#| echo: true
#| warning: false

results_dfs <- imap(
  folds_dfs,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    data <- data_dfs |> 
      select(-c(patient_id, sample_id))
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data)),
                         fold_idx)
    train_data <- data[train_idx, ]
    test_data  <- data[fold_idx, ]
    
    # Fit RSF
    fit <- rfsrc(Surv(years_to_dfs_event, 
                      dfs_status) ~ ., 
                 data = train_data,
                 ntree = trees,
                 splitrule = rule,
                 importance = TRUE)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred$predicted
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store variable importance
    imp <- fit$importance
    
    importance <- tibble(
      fold = fold_num,
      feature = names(imp),
      importance = as.numeric(imp)
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      importance = importance
    )
  }
)

predictions_dfs <- map_dfr(results_dfs, "predictions") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "all")

predictions_dfs

write_tsv(predictions_dfs,
          file = "../results/07_rsf_predictions.tsv",
          append = TRUE)

metrics_dfs <- map_dfr(results_dfs, "metrics") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "all")

metrics_dfs

write_tsv(metrics_dfs,
          file = "../results/07_rsf_results.tsv",
          append = TRUE)


importance_dfs <- map_dfr(results_dfs, "importance") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "all")

importance_dfs

write_tsv(importance_dfs,
          file = "../results/07_rsf_vimp.tsv",
          append = TRUE)
```

## No NLP data

```{r}
#| label: predict_dfs_noNLP
#| echo: true
#| warning: false

results_dfs_noNLP <- imap(
  folds_dfs_noNLP,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    data <- data_dfs_noNLP |> 
      select(-c(patient_id, sample_id))
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data)),
                         fold_idx)
    train_data <- data[train_idx, ]
    test_data  <- data[fold_idx, ]
    
    # Fit RSF
    fit <- rfsrc(Surv(years_to_dfs_event, 
                      dfs_status) ~ ., 
                 data = train_data,
                 ntree = trees,
                 splitrule = rule,
                 importance = TRUE)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred$predicted
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store variable importance
    imp <- fit$importance
    
    importance <- tibble(
      fold = fold_num,
      feature = names(imp),
      importance = as.numeric(imp)
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      importance = importance
    )
  }
)

predictions_dfs_noNLP <- map_dfr(results_dfs_noNLP, "predictions") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "noNLP")

predictions_dfs_noNLP

write_tsv(predictions_dfs_noNLP,
          file = "../results/07_rsf_predictions.tsv",
          append = TRUE)

metrics_dfs_noNLP <- map_dfr(results_dfs_noNLP, "metrics") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "noNLP")

metrics_dfs_noNLP

write_tsv(metrics_dfs_noNLP,
          file = "../results/07_rsf_results.tsv",
          append = TRUE)


importance_dfs_noNLP <- map_dfr(results_dfs_noNLP, "importance") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "noNLP")

importance_dfs_noNLP

write_tsv(importance_dfs_noNLP,
          file = "../results/07_rsf_vimp.tsv",
          append = TRUE)
```

## No genomic data

```{r}
#| label: predict_dfs_nogenomic
#| echo: true
#| warning: false

results_dfs_nogenomic <- imap(
  folds_dfs_nogenomic,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    data <- data_dfs_nogenomic |> 
      select(-c(patient_id, sample_id))
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data)),
                         fold_idx)
    train_data <- data[train_idx, ]
    test_data  <- data[fold_idx, ]
    
    # Fit RSF
    fit <- rfsrc(Surv(years_to_dfs_event, 
                      dfs_status) ~ ., 
                 data = train_data,
                 ntree = trees,
                 splitrule = rule,
                 importance = TRUE)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred$predicted
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store variable importance
    imp <- fit$importance
    
    importance <- tibble(
      fold = fold_num,
      feature = names(imp),
      importance = as.numeric(imp)
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      importance = importance
    )
  }
)

predictions_dfs_nogenomic <- map_dfr(results_dfs_nogenomic, "predictions") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "nogenomic")

predictions_dfs_nogenomic

write_tsv(predictions_dfs_nogenomic,
          file = "../results/07_rsf_predictions.tsv",
          append = TRUE)

metrics_dfs_nogenomic <- map_dfr(results_dfs_nogenomic, "metrics") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "nogenomic")

metrics_dfs_nogenomic

write_tsv(metrics_dfs_nogenomic,
          file = "../results/07_rsf_results.tsv",
          append = TRUE)


importance_dfs_nogenomic <- map_dfr(results_dfs_nogenomic, "importance") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "nogenomic")

importance_dfs_nogenomic

write_tsv(importance_dfs_nogenomic,
          file = "../results/07_rsf_vimp.tsv",
          append = TRUE)
```

## Only routine data

```{r}
#| label: predict_dfs_noNLPgenomic
#| echo: true
#| warning: false

results_dfs_noNLPgenomic <- imap(
  folds_dfs_noNLPgenomic,
  ~ {
    fold_idx <- .x
    fold_num <- .y
    
    data <- data_dfs_noNLPgenomic |> 
      select(-c(patient_id, sample_id))
    
    # Split train / test
    train_idx <- setdiff(seq_len(nrow(data)),
                         fold_idx)
    train_data <- data[train_idx, ]
    test_data  <- data[fold_idx, ]
    
    # Fit RSF
    fit <- rfsrc(Surv(years_to_dfs_event, 
                      dfs_status) ~ ., 
                 data = train_data,
                 ntree = trees,
                 splitrule = rule,
                 importance = TRUE)
    
    # Calculate risk scores
    pred <- predict(fit, 
                    newdata = test_data)
    risk <- -pred$predicted
    
    predictions <- tibble(
      fold = fold_num,
      id = test_data$patient_id,
      dfs_status = test_data$dfs_status,
      years_to_dfs_event = test_data$years_to_dfs_event,
      risk = risk
    )
    
    # Calculate concordance
    c_index <- concordance(
      Surv(test_data$years_to_dfs_event, 
           test_data$dfs_status) ~ risk
    )$concordance
    
    
    # Calculate time-dependent AUCs
    compute_auc <- function(t) {
      status_t <- case_when(
        test_data$years_to_dfs_event <= t & test_data$dfs_status == 1 ~ 1,
        test_data$years_to_dfs_event >= t ~ 0,
        TRUE ~ NA_real_
      )
      keep <- !is.na(status_t)
      if (sum(status_t[keep] == 1) == 0 || sum(status_t[keep] == 0) == 0) {
        NA_real_
      } else {
        as.numeric(
          roc(response = status_t[keep],
              predictor = risk[keep],
              quiet = TRUE)$auc
        )
      }
    }
    
    auc_12_months <- compute_auc(1)
    auc_18_months <- compute_auc(1.5)
    auc_24_months <- compute_auc(2)
    auc_36_months <- compute_auc(3)
    
    metrics <- tibble(
      fold = fold_num,
      c_index = c_index,
      auc_12_months = auc_12_months,
      auc_18_months = auc_18_months,
      auc_24_months = auc_24_months,
      auc_36_months = auc_36_months
    )
    
    # Store variable importance
    imp <- fit$importance
    
    importance <- tibble(
      fold = fold_num,
      feature = names(imp),
      importance = as.numeric(imp)
    )
    
    # Return all three tibbles in a list
    list(
      predictions = predictions,
      metrics = metrics,
      importance = importance
    )
  }
)

predictions_dfs_noNLPgenomic <- map_dfr(results_dfs_noNLPgenomic, "predictions") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "noNLPgenomic")

predictions_dfs_noNLPgenomic

write_tsv(predictions_dfs_noNLPgenomic,
          file = "../results/07_rsf_predictions.tsv",
          append = TRUE)

metrics_dfs_noNLPgenomic <- map_dfr(results_dfs_noNLPgenomic, "metrics") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "noNLPgenomic")

metrics_dfs_noNLPgenomic

write_tsv(metrics_dfs_noNLPgenomic,
          file = "../results/07_rsf_results.tsv",
          append = TRUE)


importance_dfs_noNLPgenomic <- map_dfr(results_dfs_noNLPgenomic, "importance") |> 
  mutate(model = "RSF",
         outcome = "DFS",
         features = "noNLPgenomic")

importance_dfs_noNLPgenomic

write_tsv(importance_dfs_noNLPgenomic,
          file = "../results/07_rsf_vimp.tsv",
          append = TRUE)
```
