---
title: "Post-hoc model evaluation"
subtitle: "Forward stepwise Cox model with clinical data only"
author: "Puck Quarles van Ufford"
date: today
format: html
---

# Set up

```{r}
#| label: packages
#| message: false
#| echo: true

library("tidyverse")
library("patchwork")
library("survival")
library("survminer")
```

# Load data

```{r}
#| label: load_data
#| message: false
#| echo: true

data_os <- read_tsv(file = "../data/03_data_train_os.tsv")
data_dfs <- read_tsv(file = "../data/03_data_train_dfs.tsv")
```

# Load results

```{r}
#| label: load_results
#| message: false
#| echo: true

risk_scores <- read_tsv(file = "../results/06_predictions_100_max.tsv",
                        col_names = c("fold",
                                      "patient_id",
                                      "status",
                                      "years_to_event",
                                      "risk",
                                      "model",
                                      "outcome",
                                      "feature_set"))

coefs <- read_tsv(file = "../results/06_coefs_100_max.tsv",
                  col_names = c("fold",
                                "feature",
                                "beta",
                                "p",
                                "model",
                                "outcome",
                                "feature_set"))
```

# Assess clinical utility of risk scores

```{r}
#| label: utility_risk_os
#| echo: true

risk_scores_os <- risk_scores |> 
  filter(outcome == "OS",
         feature_set == "noNLPgenomic") |> 
  mutate(risk = -risk,
         risk_quartile = ntile(risk, 4),
         risk_quartile = factor(
           risk_quartile,
           levels = 1:4,
           labels = c("Q1", "Q2", "Q3", "Q4")))

fit_os <- survfit(Surv(years_to_event,
                       status) ~ risk_quartile,
                  data = risk_scores_os)

ggsurvplot(
  fit = fit_os,
  data = risk_scores_os,
  title = "Kaplan-Meier plot OS risk score",
  xlab = "Time (years after surgery)",
  ylab = "OS probability",
  xlim = c(0, 5),
  ylim = c(0, 1),
  break.x.by = 1,
  legend = "bottom",
  risk.table = F,
  pval = TRUE,
  pval.method = TRUE,
  palette = c("#648FFF",
              "#785EF0",
              "#DC267F",
              "#FE6100"),
  ggtheme = theme_bw()
)  
  
ggsave("../results/09_KM_OS.png",
       width = 8,
       height = 4.5)
```

```{r}
#| label: utility_risk_dfs
#| echo: true

risk_scores_dfs <- risk_scores |> 
  filter(outcome == "DFS",
         feature_set == "noNLPgenomic") |> 
  mutate(risk = -risk,
         risk_quartile = ntile(risk, 4),
         risk_quartile = factor(
           risk_quartile,
           levels = 1:4,
           labels = c("Q1", "Q2", "Q3", "Q4")))

fit_dfs <- survfit(Surv(years_to_event,
                       status) ~ risk_quartile,
                  data = risk_scores_dfs)

ggsurvplot(
  fit = fit_dfs,
  data = risk_scores_dfs,
  title = "Kaplan-Meier plot DFS risk score",
  xlab = "Time (years after surgery)",
  ylab = "DFS probability",
  xlim = c(0, 5),
  ylim = c(0, 1),
  break.x.by = 1,
  legend = "bottom",
  risk.table = F,
  pval = TRUE,
  pval.method = TRUE,
  palette = c("#648FFF",
              "#785EF0",
              "#DC267F",
              "#FE6100"),
  ggtheme = theme_bw()
)  
  
ggsave("../results/09_KM_DFS.png",
       width = 8,
       height = 4.5)
```

# Explore feature importance

```{r}
#| label: features_os
#| echo: true

coefs_os <- coefs |> 
  filter(outcome == "OS",
         feature_set == "noNLPgenomic") |> 
  mutate(se = abs(beta) / qnorm (1 - p/2),
         hr = exp(beta),
         hr_lower = exp(beta - 1.96*se),
         hr_upper = exp(beta + 1-96*se))

coefs_os_summary <- coefs_os |> 
  group_by(feature) |> 
  summarise(
    beta_mean = mean(beta),
    hr = exp(beta_mean),
    hr_lower = exp(quantile(beta, 0.025)),
    hr_upper = exp(quantile(beta, 0.975)),
    abs_log_hr = abs(log(hr)),
    .groups = "drop"
  )

top_features_os <- coefs_os_summary |> 
  slice_max(abs_log_hr,
            n = 20) |> 
  arrange(desc(abs_log_hr)) |> 
  pull(feature)

p1 <- coefs_os_summary |> 
  filter(feature %in% top_features_os) |> 
  mutate(feature = case_when(
    feature == "ethnicity_simplified_spanish_hispanic" ~ "Ethnicity: Spanish/Hispanic",
    feature == "ethnicity_simplified_non_spanish_non_hispanic" ~ "Ethnicity: not Spanish/Hispanic",
    feature == "tumor_purity_na" ~ "Missing tumor purity",
    feature == "oncotree_code_coadread" ~ "Cancer type: COADREAD",
    feature == "oncotree_code_coad" ~ "Cancer type: COAD",
    feature == "oncotree_code_read" ~ "Cancer type: READ",
    feature == "oncotree_code_macr" ~ "Cancer type: MACR",
    feature == "race_simplified_other" ~ "Race: other",
    feature == "gene_panel_impact341" ~ "Gene panel: IMPACT341",
    feature == "investigational_0" ~ "No investigational treatments",
    feature == "msi_type_indeterminate" ~ "MSI: indeterminate",
    feature == "race_simplified_asian" ~ "Race: Asian",
    feature == "primary_site_cecum" ~ "Primary site: cecum",
    feature == "early_onset" ~ "Early onset",
    feature == "biologic_0" ~ "No biological treatments",
    feature == "primary_site_rectum" ~ "Primary site: rectum",
    feature == "gene_panel_impact410" ~ "Gene panel: IMPACT410",
    feature == "race_simplified_white" ~ "Race: White",
    feature == "primary_site_descending_colon" ~ "Primary site: descending colon",
    feature == "msi_type_stable" ~ "MSI: stable",
    TRUE ~ feature
  )) |> 
  ggplot(mapping = aes(x = hr, 
                       y = reorder(feature,
                                   abs_log_hr))) +
  geom_point() +
  geom_errorbarh(aes(xmin = hr_lower, 
                     xmax = hr_upper), 
                 height = 0.2) +
  geom_vline(xintercept = 1, 
             linetype = "dashed") +
  labs(x = "HR (95% CI)",
       y = NULL) +
  theme_bw() + 
  scale_x_log10()

selection_freq_os <- coefs_os |> 
  group_by(feature) |> 
  summarise(selection_freq = n()) |> 
  left_join(coefs_os_summary,
            by = join_by(feature))

p2 <- selection_freq_os |> 
  filter(feature %in% top_features_os) |> 
  ggplot(mapping = aes(x = selection_freq, 
                       y = reorder(feature,
                                   abs_log_hr))) +
  geom_col() +
  labs(x = "Selected in n folds",
       y = NULL) +
  theme_bw() +
  theme(axis.text.y  = element_blank(),
        axis.ticks.y = element_blank())

p1 + p2 +
  plot_layout(widths = c(3, 2)) +
  plot_annotation(
    title = "Hazard ratio and stability of top 20 clinical predictors OS",
    theme = theme(
      plot.title = element_text(hjust = 0.5)))

ggsave("../results/09_features_os.png",
       width = 8,
       height = 4)
```

```{r}
#| label: features_dfs
#| echo: true

coefs_dfs <- coefs |> 
  filter(outcome == "DFS",
         feature_set == "noNLPgenomic") |> 
  mutate(se = abs(beta) / qnorm (1 - p/2),
         hr = exp(beta),
         hr_lower = exp(beta - 1.96*se),
         hr_upper = exp(beta + 1-96*se))

coefs_dfs_summary <- coefs_dfs |> 
  group_by(feature) |> 
  summarise(
    beta_mean = mean(beta),
    hr = exp(beta_mean),
    hr_lower = exp(quantile(beta, 0.025)),
    hr_upper = exp(quantile(beta, 0.975)),
    abs_log_hr = abs(log(hr)),
    .groups = "drop"
  )

top_features_dfs <- coefs_dfs_summary |> 
  slice_max(abs_log_hr,
            n = 20) |> 
  arrange(desc(abs_log_hr)) |> 
  pull(feature)

p3 <- coefs_dfs_summary |> 
  filter(feature %in% top_features_dfs) |> 
    mutate(feature = case_when(
    feature == "chemo_0" ~ "No chemotherapy",
    feature == "chemo_1" ~ "Chemotherapy",
    feature == "investigational_0" ~ "No investigational treatments",
    feature == "hormone_0" ~ "No hormonal treatments",
    feature == "race_simplified_asian" ~ "Race: Asian",
    feature == "primary_site_descending_colon" ~ "Primary site: descending colon",
    feature == "ethnicity_simplified_spanish_hispanic" ~ "Ethnicity: Spanish/Hispanic",
    feature == "oncotree_code_read" ~ "Cancer type: READ",
    feature == "clinical_group_simplified_na" ~ "Missing clinical group",
    feature == "race_simplified_white" ~ "Race: White",
    feature == "primary_site_rectum" ~ "Primary site: rectum",
    feature == "race_simplified_black" ~ "Race: Black",
    feature == "primary_site_cecum" ~ "Primary site: cecum",
    feature == "gene_panel_impact341" ~ "Gene panel: IMPACT341",
    feature == "gene_panel_impact468" ~ "Gene panel: IMPACT468",
    feature == "biologic_0" ~ "No biological treatments",
    feature == "cea_na" ~ "Missing CEA",
    feature == "ethnicity_simplified_non_spanish_non_hispanic" ~ "Ethnicity: not Spanish/Hispanic",
    feature == "primary_site_sigmoid_colon" ~ "Primary site: sigmoid colon",
    feature == "gene_panel_impact410" ~ "Gene panel: IMPACT410",
    TRUE ~ feature
  )) |> 
  ggplot(mapping = aes(x = hr, 
                       y = reorder(feature,
                                   abs_log_hr))) +
  geom_point() +
  geom_errorbarh(aes(xmin = hr_lower, 
                     xmax = hr_upper), 
                 height = 0.2) +
  geom_vline(xintercept = 1, 
             linetype = "dashed") +
  labs(x = "HR (95% CI)",
       y = NULL) +
  theme_bw() + 
  scale_x_log10()

selection_freq_dfs <- coefs_dfs |> 
  group_by(feature) |> 
  summarise(selection_freq = n()) |> 
  left_join(coefs_dfs_summary,
            by = join_by(feature))

p4 <- selection_freq_dfs |> 
  filter(feature %in% top_features_dfs) |> 
  ggplot(mapping = aes(x = selection_freq, 
                       y = reorder(feature,
                                   abs_log_hr))) +
  geom_col() +
  labs(x = "Fraction of folds selected",
       y = NULL) +
  theme_bw() +
  theme(axis.text.y  = element_blank(),
        axis.ticks.y = element_blank())

p3 + p4 +
  plot_layout(widths = c(3, 2)) +
  plot_annotation(
    title = "Hazard ratio and stability of top 20 clinical predictors DFS",
    theme = theme(
      plot.title = element_text(hjust = 0.5)))

ggsave("../results/09_features_dfs.png",
       width = 8,
       height = 4)
```

## Correlation among key features

```{r}
#| label: correlation_os_features
#| echo: true

corr_os <- data_os  |> 
  select(all_of(top_features_os)) |> 
  drop_na()

corr_os_mat <- cor(corr_os, 
                    use = "pairwise.complete.obs", 
                    method = "spearman")

corr_os_long <- as.data.frame(corr_os_mat) |> 
  rownames_to_column("feature_x") |> 
  pivot_longer(cols = -feature_x,
               names_to = "feature_y",
               values_to = "correlation") 

order <- hclust(dist(1 - corr_os_mat))$order
ordered_features <- colnames(corr_os_mat)[order]

corr_os_long <- corr_os_long |> 
  mutate(feature_x = factor(feature_x, levels = ordered_features),
         feature_y = factor(feature_y, levels = ordered_features),
         feature_x = case_when(
           feature_x == "ethnicity_simplified_spanish_hispanic" ~ "Ethnicity: Spanish/Hispanic",
           feature_x == "ethnicity_simplified_non_spanish_non_hispanic" ~ "Ethnicity: not Spanish/Hispanic",
           feature_x == "tumor_purity_na" ~ "Missing tumor purity",
           feature_x == "oncotree_code_coadread" ~ "Cancer type: COADREAD",
           feature_x == "oncotree_code_coad" ~ "Cancer type: COAD",
           feature_x == "oncotree_code_read" ~ "Cancer type: READ",
           feature_x == "oncotree_code_macr" ~ "Cancer type: MACR",
           feature_x == "race_simplified_other" ~ "Race: other",
           feature_x == "gene_panel_impact341" ~ "Gene panel: IMPACT341",
           feature_x == "investigational_0" ~ "No investigational treatments",
           feature_x == "msi_type_indeterminate" ~ "MSI: indeterminate",
           feature_x == "race_simplified_asian" ~ "Race: Asian",
           feature_x == "primary_site_cecum" ~ "Primary site: cecum",
           feature_x == "early_onset" ~ "Early onset",
           feature_x == "biologic_0" ~ "No biological treatments",
           feature_x == "primary_site_rectum" ~ "Primary site: rectum",
           feature_x == "gene_panel_impact410" ~ "Gene panel: IMPACT410",
           feature_x == "race_simplified_white" ~ "Race: White",
           feature_x == "primary_site_descending_colon" ~ "Primary site: descending colon",
           feature_x == "msi_type_stable" ~ "MSI: stable",
           TRUE ~ feature_y),
         feature_y = case_when(
           feature_y == "ethnicity_simplified_spanish_hispanic" ~ "Ethnicity: Spanish/Hispanic",
           feature_y == "ethnicity_simplified_non_spanish_non_hispanic" ~ "Ethnicity: not Spanish/Hispanic",
           feature_y == "tumor_purity_na" ~ "Missing tumor purity",
           feature_y == "oncotree_code_coadread" ~ "Cancer type: COADREAD",
           feature_y == "oncotree_code_coad" ~ "Cancer type: COAD",
           feature_y == "oncotree_code_read" ~ "Cancer type: READ",
           feature_y == "oncotree_code_macr" ~ "Cancer type: MACR",
           feature_y == "race_simplified_other" ~ "Race: other",
           feature_y == "gene_panel_impact341" ~ "Gene panel: IMPACT341",
           feature_y == "investigational_0" ~ "No investigational treatments",
           feature_y == "msi_type_indeterminate" ~ "MSI: indeterminate",
           feature_y == "race_simplified_asian" ~ "Race: Asian",
           feature_y == "primary_site_cecum" ~ "Primary site: cecum",
           feature_y == "early_onset" ~ "Early onset",
           feature_y == "biologic_0" ~ "No biological treatments",
           feature_y == "primary_site_rectum" ~ "Primary site: rectum",
           feature_y == "gene_panel_impact410" ~ "Gene panel: IMPACT410",
           feature_y == "race_simplified_white" ~ "Race: White",
           feature_y == "primary_site_descending_colon" ~ "Primary site: descending colon",
           feature_y == "msi_type_stable" ~ "MSI: stable",
           TRUE ~ feature_y))

corr_os_long |> 
  ggplot(mapping = aes(x = feature_x, 
                       y = feature_y, 
                       fill = correlation)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(
    low = "#648FFF",
    mid = "white",
    high = "#FE6100",
    midpoint = 0,
    limits = c(-1, 1)) +
  labs(
    x = NULL,
    y = NULL,
    title = "Spearman correlation of top 20 clinical predictors OS") +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid = element_blank())

ggsave("../results/09_corr_os.png",
       width = 7,
       height = 7)
```

```{r}
#| label: correlation_dfs_features
#| echo: true

corr_dfs <- data_dfs  |> 
  select(all_of(top_features_dfs)) |> 
  drop_na()

corr_dfs_mat <- cor(corr_dfs, 
                    use = "pairwise.complete.obs", 
                    method = "spearman")

corr_dfs_long <- as.data.frame(corr_dfs_mat) |> 
  rownames_to_column("feature_x") |> 
  pivot_longer(cols = -feature_x,
               names_to = "feature_y",
               values_to = "correlation")

order <- hclust(dist(1 - corr_dfs_mat))$order
ordered_features <- colnames(corr_dfs_mat)[order]

corr_dfs_long <- corr_dfs_long |> 
  mutate(feature_x = factor(feature_x, levels = ordered_features),
         feature_y = factor(feature_y, levels = ordered_features),
         feature_x = case_when(
           feature_x == "chemo_0" ~ "No chemotherapy",
           feature_x == "chemo_1" ~ "Chemotherapy",
           feature_x == "investigational_0" ~ "No investigational treatments",
           feature_x == "hormone_0" ~ "No hormonal treatments",
           feature_x == "race_simplified_asian" ~ "Race: Asian",
           feature_x == "primary_site_descending_colon" ~ "Primary site: descending colon",
           feature_x == "ethnicity_simplified_spanish_hispanic" ~ "Ethnicity: Spanish/Hispanic",
           feature_x == "oncotree_code_read" ~ "Cancer type: READ",
           feature_x == "clinical_group_simplified_na" ~ "Missing clinical group",
           feature_x == "race_simplified_white" ~ "Race: White",
           feature_x == "primary_site_rectum" ~ "Primary site: rectum",
           feature_x == "race_simplified_black" ~ "Race: Black",
           feature_x == "primary_site_cecum" ~ "Primary site: cecum",
           feature_x == "gene_panel_impact341" ~ "Gene panel: IMPACT341",
           feature_x == "gene_panel_impact468" ~ "Gene panel: IMPACT468",
           feature_x == "biologic_0" ~ "No biological treatments",
           feature_x == "cea_na" ~ "Missing CEA",
           feature_x == "ethnicity_simplified_non_spanish_non_hispanic" ~ "Ethnicity: not Spanish/Hispanic",
           feature_x == "primary_site_sigmoid_colon" ~ "Primary site: sigmoid colon",
           feature_x == "gene_panel_impact410" ~ "Gene panel: IMPACT410",
           TRUE ~ feature_x),
         feature_y = case_when(
           feature_y == "chemo_0" ~ "No chemotherapy",
           feature_y == "chemo_1" ~ "Chemotherapy",
           feature_y == "investigational_0" ~ "No investigational treatments",
           feature_y == "hormone_0" ~ "No hormonal treatments",
           feature_y == "race_simplified_asian" ~ "Race: Asian",
           feature_y == "primary_site_descending_colon" ~ "Primary site: descending colon",
           feature_y == "ethnicity_simplified_spanish_hispanic" ~ "Ethnicity: Spanish/Hispanic",
           feature_y == "oncotree_code_read" ~ "Cancer type: READ",
           feature_y == "clinical_group_simplified_na" ~ "Missing clinical group",
           feature_y == "race_simplified_white" ~ "Race: White",
           feature_y == "primary_site_rectum" ~ "Primary site: rectum",
           feature_y == "race_simplified_black" ~ "Race: Black",
           feature_y == "primary_site_cecum" ~ "Primary site: cecum",
           feature_y == "gene_panel_impact341" ~ "Gene panel: IMPACT341",
           feature_y == "gene_panel_impact468" ~ "Gene panel: IMPACT468",
           feature_y == "biologic_0" ~ "No biological treatments",
           feature_y == "cea_na" ~ "Missing CEA",
           feature_y == "ethnicity_simplified_non_spanish_non_hispanic" ~ "Ethnicity: not Spanish/Hispanic",
           feature_y == "primary_site_sigmoid_colon" ~ "Primary site: sigmoid colon",
           feature_y == "gene_panel_impact410" ~ "Gene panel: IMPACT410",
           TRUE ~ feature_y))

corr_dfs_long |> 
  ggplot(mapping = aes(x = feature_x, 
                       y = feature_y, 
                       fill = correlation)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(
    low = "#648FFF",
    mid = "white",
    high = "#FE6100",
    midpoint = 0,
    limits = c(-1, 1)) +
  labs(
    x = NULL,
    y = NULL,
    title = "Spearman correlation of top 20 clinical predictors DFS") +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid = element_blank())

ggsave("../results/09_corr_dfs.png",
       width = 7,
       height = 7)
```
